version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=gtrp
      - MYSQL_USER=gtrp
      - MYSQL_PASSWORD=gtrp
      - MYSQL_ROOT_PASSWORD=gtrp
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=1
      - DATABASE_URL=mysql://gtrp:gtrp@db/gtrp
    depends_on:
      - db