# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('TX', 'Text'), ('AU', 'Audio'), ('VD', 'Video')], default='TX', max_length=2)),
                ('full_text', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtr_site.Person')),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtr_site.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtr_site.Statement'),
        ),
    ]
