# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0002_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='statement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gtr_site.Statement'),
            preserve_default=False,
        ),
    ]
