# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0003_context_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='statement',
        ),
        migrations.AddField(
            model_name='keyword',
            name='statement',
            field=models.ManyToManyField(to='gtr_site.Statement'),
        ),
    ]
