# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0008_resources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
    ]
