# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0010_statement_produced_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='access',
            field=models.CharField(choices=[('AL', 'All users'), ('HC', 'Haverford College users only')], default='AL', max_length=2),
        ),
    ]
