# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0012_auto_20170719_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='access',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='produced_by',
        ),
        migrations.AddField(
            model_name='statement',
            name='statement_contexts',
            field=models.ManyToManyField(to='gtr_site.Context'),
        ),
        migrations.AddField(
            model_name='statement',
            name='statement_keywords',
            field=models.ManyToManyField(to='gtr_site.Keyword'),
        ),
    ]
