# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0013_auto_20170720_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyConPairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_name', models.CharField(max_length=250)),
                ('context_in_pair', models.ManyToManyField(to='gtr_site.Context')),
                ('keyword_in_pair', models.ManyToManyField(to='gtr_site.Keyword')),
                ('statement', models.ManyToManyField(to='gtr_site.Statement')),
            ],
        ),
    ]
