# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0015_auto_20170722_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement_contexts',
            field=models.ManyToManyField(blank=True, to='gtr_site.Context'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement_keywords',
            field=models.ManyToManyField(blank=True, to='gtr_site.Keyword'),
        ),
    ]
