# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0020_statement_full_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordInContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexts', models.ManyToManyField(related_name='keyword_context', to='gtr_site.Keyword')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtr_site.Keyword')),
            ],
        ),
        migrations.AddField(
            model_name='statement',
            name='keywords',
            field=models.ManyToManyField(to='gtr_site.KeywordInContext'),
        ),
    ]
