# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0021_auto_20170728_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='issue_date',
            field=models.DateField(verbose_name='Statement Issue Date'),
        ),
    ]
