# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0022_auto_20170729_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='issue_date',
            field=models.DateField(verbose_name='Issue-Date'),
        ),
    ]
