# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0023_auto_20170729_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='solokeywords',
            field=models.ManyToManyField(related_name='statement_keywords', to='gtr_site.Keyword'),
        ),
    ]
