# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0024_statement_solokeywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='solokeywords',
        ),
    ]
