# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0026_auto_20170809_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
