# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0027_auto_20170810_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='media_type',
            field=models.CharField(choices=[('TX', 'Text'), ('AU', 'Audio'), ('VD', 'Video'), ('TW', 'Tweet')], default='TX', max_length=2),
        ),
    ]
