# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0028_auto_20170816_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='fulltext',
            field=models.TextField(blank=True),
        ),
    ]
