# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0030_auto_20171106_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='summary',
            new_name='pdf_text',
        ),
    ]
