# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0031_auto_20171108_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='pdf_text',
            field=models.TextField(blank=True, verbose_name='PDF text'),
        ),
    ]
