# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-26 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtr_site', '0033_list'),
    ]

    operations = [
        migrations.RemoveField(
           model_name='list',
           name='user',
        ),
    ]
